// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgCNB7m5tqyJvNRgh2OJ7o9ME7bIF3y8k',
    appId: '1:926750057177:web:92c17e21bab5655ac514c8',
    messagingSenderId: '926750057177',
    projectId: 'proyectocacao-a258b',
    authDomain: 'proyectocacao-a258b.firebaseapp.com',
    databaseURL: 'https://proyectocacao-a258b-default-rtdb.firebaseio.com',
    storageBucket: 'proyectocacao-a258b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzWmsbuVai_sygtNbp_Mb_-6zBejI-v04',
    appId: '1:926750057177:android:bbfeaca262f37dc5c514c8',
    messagingSenderId: '926750057177',
    projectId: 'proyectocacao-a258b',
    databaseURL: 'https://proyectocacao-a258b-default-rtdb.firebaseio.com',
    storageBucket: 'proyectocacao-a258b.firebasestorage.app',
  );
}
